Style/Documentation:
  Enabled: false
Style/FormatString:
  Enabled: false
Style/Next:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
